services:
  moodle:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: moodle-app
    depends_on:
      - db
    volumes:
      - ./moodle:/var/www/html/moodle
      - ./moodledata:/var/www/moodledata
    environment:
      - MOODLE_DOCKER_DBHOST=db
      - MOODLE_DOCKER_DBUSER=root
      - MOODLE_DOCKER_DBPASS=Root@123
      - MOODLE_DOCKER_DBNAME=moodle_lms
    networks:
      - rtc_net

  nginx:
    image: nginx:latest
    container_name: moodle-nginx
    depends_on:
      - moodle
    ports:
      - "8080:80"
    volumes:
      - ./moodle:/var/www/html/moodle
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./moodledata:/var/www/moodledata
    networks:
      - rtc_net

  db:
    image: mysql:8.4
    container_name: moodle-db
    restart: always
    command: --default-authentication-plugin=caching_sha2_password
    environment:
      MYSQL_ROOT_PASSWORD: Root@123
      MYSQL_DATABASE: moodle_lms
      MYSQL_USER: root
      MYSQL_PASSWORD: Root@123
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - rtc_net

volumes:
  db_data:

networks:
  rtc_net:
    external: true
