version: "3.9"

services:
  moodle-db:
    image: mysql:8.4
    container_name: moodle-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Root@123
      MYSQL_DATABASE: moodle_lms
      MYSQL_USER: root
      MYSQL_PASSWORD: Root@123
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - rtc_net

  moodle-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: moodle-php:8.3-fpm
    container_name: moodle-app
    restart: always
    depends_on:
      - moodle-db
    volumes:
      - ./moodle:/var/www/moodle
      - ./moodledata:/var/www/moodledata
    networks:
      - rtc_net

  moodle-nginx:
    image: nginx:latest
    container_name: moodle-nginx
    restart: always
    depends_on:
      - moodle-app
    ports:
      - "8800:80"
    volumes:
      - ./moodle:/var/www/moodle
      - ./moodledata:/var/www/moodledata
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - rtc_net

volumes:
  db_data:

networks:
  rtc_net:
    external: true
