server {
    listen 80;
    server_name _;

    root /var/www/moodle/;
    index index.php index.html;

    client_max_body_size 100M;

    location /moodle/ {
        try_files $uri $uri/ /moodle/index.php?$query_string;
    }

    location ~ ^/moodle/.*\.php$ {
        include fastcgi_params;
        fastcgi_pass __SERVICE_MOODLE_APP__:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
    }

    location = / {
        return 301 /moodle/;
    }

    location ~* \.(jpg|jpeg|gif|png|css|js|ico|svg|woff|woff2)$ {
        expires 30d;
        log_not_found off;
        access_log off;
    }

    location ~ /\. {
        deny all;
    }
}
